const { app, BrowserWindow, BrowserView, ipcMain, session, Menu, net } = require('electron');
const path = require('path');
const fs = require('fs');
const AdmZip = require('adm-zip');

const CHROME_UA = `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/${process.versions.chrome || '150.0.0.0'} Safari/537.36`;
const CWS_HOSTS = new Set(['chromewebstore.google.com', 'chrome.google.com']);
const filter = { urls: ['*://*/*'] };
const blocked = new Set(['doubleclick.net','googlesyndication.com','googleadservices.com','adnxs.com','adsrvr.org','scorecardresearch.com','zedo.com']);
const SIDEBAR_WIDTH = 72;

let win;
let extensionStoreFile;
let activeTabId = null;
let nextTabId = 1;
const tabs = new Map();
const extensions = new Map();

function shouldBlock(url) { try { const host = new URL(url).hostname.replace(/^www\./, '').toLowerCase(); return blocked.has(host) || [...blocked].some(domain => host.endsWith(`.${domain}`)); } catch { return false; } }
function isCwsUrl(url) { try { return CWS_HOSTS.has(new URL(url).hostname.toLowerCase()); } catch { return false; } }
function readInstalledExtensions() { try { if (!fs.existsSync(extensionStoreFile)) return []; const data = JSON.parse(fs.readFileSync(extensionStoreFile, 'utf8')); return Array.isArray(data) ? data : []; } catch { return []; } }
function writeInstalledExtensions() { fs.mkdirSync(path.dirname(extensionStoreFile), { recursive: true }); fs.writeFileSync(extensionStoreFile, JSON.stringify([...extensions.values()], null, 2), 'utf8'); }
function uiProgress(payload) { win?.webContents.send('extension-install-progress', payload); }
function cleanTitle(title, url) { if (title && title.trim()) return title.trim(); try { return new URL(url).hostname || 'Yeni sekme'; } catch { return 'Yeni sekme'; } }
function tabSnapshot(tab) { return { id: tab.id, title: tab.title, url: tab.url, loading: Boolean(tab.loading), active: tab.id === activeTabId, canGoBack: tab.view.webContents.canGoBack(), canGoForward: tab.view.webContents.canGoForward() }; }
function emitTabs() { if (!win || win.isDestroyed()) return; win.webContents.send('tabs-updated', [...tabs.values()].map(tabSnapshot)); if (activeTabId) win.webContents.send('active-tab', activeTabId); }
function activeTab() { return activeTabId ? tabs.get(activeTabId) : null; }
function getBounds() { const b = win.getBounds(); return { x: SIDEBAR_WIDTH, y: 112, width: Math.max(0, b.width - SIDEBAR_WIDTH), height: Math.max(0, b.height - 112) }; }
function layoutView(tab) { if (!tab || tab.view.isDestroyed()) return; tab.view.setBounds(getBounds()); tab.view.setAutoResize({ width: true, height: true }); }
function attachTab(tab) { if (!tab) return; layoutView(tab); win.setBrowserView(tab.view); activeTabId = tab.id; emitTabs(); }
function detachTab(tab) { if (!tab) return; try { if (win.getBrowserView() === tab.view) win.setBrowserView(null); } catch {} }

function parseCrx(buffer) { const b = Buffer.from(buffer); if (b.length < 16 || b.subarray(0, 4).toString() !== 'Cr24') throw new Error('Geçersiz CRX paketi'); const version = b.readUInt32LE(4); if (version === 2) { const pub = b.readUInt32LE(8), sig = b.readUInt32LE(12), offset = 16 + pub + sig; if (offset >= b.length) throw new Error('Bozuk CRX2 paketi'); return b.subarray(offset); } if (version === 3) { const header = b.readUInt32LE(8), offset = 12 + header; if (offset >= b.length) throw new Error('Bozuk CRX3 paketi'); return b.subarray(offset); } throw new Error(`Desteklenmeyen CRX sürümü: ${version}`); }
function readManifest(dir) { const file = path.join(dir, 'manifest.json'); if (!fs.existsSync(file)) throw new Error('Uzantı manifest.json içermiyor'); const manifest = JSON.parse(fs.readFileSync(file, 'utf8')); if (!manifest.name || !manifest.version || !manifest.manifest_version) throw new Error('Geçersiz uzantı manifesti'); if (![2, 3].includes(Number(manifest.manifest_version))) throw new Error(`Manifest Version ${manifest.manifest_version} GenişKapı tarafından desteklenmiyor`); return manifest; }
function showExtensionIncompatibility(name, reason) { if (!win || win.isDestroyed()) return; const dialog = new BrowserWindow({ width: 520, height: 430, minWidth: 460, minHeight: 380, parent: win, modal: true, resizable: false, backgroundColor: '#060b13', title: 'GenişKapı • Eklenti uyumluluğu', webPreferences: { contextIsolation: true, sandbox: true, nodeIntegration: false } }); const params = new URLSearchParams({ name: name || 'Bu eklenti', reason: String(reason || 'Uyumluluk denetimi başarısız.') }); dialog.loadFile(path.join(__dirname, 'extension-error.html'), { query: Object.fromEntries(params.entries()) }); dialog.setMenuBarVisibility(false); }
async function downloadCrx(id) { const url = `https://clients2.google.com/service/update2/crx?response=redirect&prodversion=${encodeURIComponent(process.versions.chrome || '150.0.0.0')}&acceptformat=crx3,crx2&x=id%3D${encodeURIComponent(id)}%26uc`; const response = await net.fetch(url, { headers: { 'User-Agent': CHROME_UA, Accept: '*/*' } }); if (!response.ok) throw new Error(`Chrome Web Store indirme başarısız (${response.status})`); return Buffer.from(await response.arrayBuffer()); }
async function installChromeWebStoreExtension(id, storeUrl = '') { id = String(id || '').toLowerCase(); if (!/^[a-z]{32}$/.test(id)) throw new Error('Geçerli Chrome Web Store uzantı kimliği bulunamadı'); if (extensions.has(id)) return { ok: true, alreadyInstalled: true, extension: extensions.get(id) }; uiProgress({ id, stage: 'download', progress: 5, text: 'Uzantı indiriliyor…' }); const crx = await downloadCrx(id); uiProgress({ id, stage: 'downloaded', progress: 30, text: 'Paket alındı' }); const zip = parseCrx(crx); const baseDir = path.join(app.getPath('userData'), 'extensions'); const finalDir = path.join(baseDir, id); const tempDir = path.join(baseDir, `${id}.installing-${Date.now()}`); fs.mkdirSync(baseDir, { recursive: true }); fs.mkdirSync(tempDir, { recursive: true }); let extensionName = 'Bu eklenti'; try { new AdmZip(zip).extractAllTo(tempDir, true); const manifest = readManifest(tempDir); extensionName = manifest.name || extensionName; uiProgress({ id, stage: 'unpack', progress: 60, text: 'Uzantı hazırlanıyor…' }); if (fs.existsSync(finalDir)) fs.rmSync(finalDir, { recursive: true, force: true }); fs.renameSync(tempDir, finalDir); const loaded = await session.defaultSession.loadExtension(finalDir, { allowFileAccess: true }).catch(error => { throw new Error(`GenişKapı bu uzantıyı yükleyemedi: ${error.message}`); }); const record = { id: loaded.id || id, name: extensionName, version: manifest.version, manifestVersion: manifest.manifest_version, path: finalDir, source: 'Chrome Web Store', storeUrl: storeUrl || `https://chromewebstore.google.com/detail/${id}` }; extensions.set(record.id, record); writeInstalledExtensions(); win?.webContents.send('extension-installed', record); uiProgress({ id: record.id, stage: 'done', progress: 100, text: `${record.name} kuruldu` }); return { ok: true, extension: record }; } catch (error) { try { fs.rmSync(tempDir, { recursive: true, force: true }); } catch {} try { fs.rmSync(finalDir, { recursive: true, force: true }); } catch {} showExtensionIncompatibility(extensionName, error.message); win?.webContents.send('extension-install-error', { id, error: error.message, incompatible: true }); return { ok: false, incompatible: true, error: error.message }; } }
async function restoreExtensions() { for (const item of readInstalledExtensions()) { try { if (!item.path || !fs.existsSync(item.path)) continue; const manifest = readManifest(item.path); const loaded = await session.defaultSession.loadExtension(item.path, { allowFileAccess: true }); extensions.set(loaded.id || item.id, { ...item, id: loaded.id || item.id, name: manifest.name, version: manifest.version }); } catch (error) { console.warn('[GenişKapı] Uzantı yüklenemedi:', item.id, error.message); } } writeInstalledExtensions(); }
function injectCwsBridge(contents) { contents.on('did-finish-load', async () => { if (!isCwsUrl(contents.getURL())) return; const bridge = `(()=>{const getId=()=>{const m=location.pathname.match(/\\/detail\\/[^/]+\\/([a-z]{32})/i);return m?m[1].toLowerCase():null};const hide=()=>document.querySelectorAll('body *').forEach(el=>{if(!(el instanceof HTMLElement)||el.children.length>4)return;const t=(el.innerText||'').trim();if(t&&t.length<180&&/(chrome|google chrome).*(gerek|gerekiyor|required|needed)/i.test(t))el.style.display='none'});const mark=()=>document.querySelectorAll('button,[role="button"],a').forEach(el=>{const t=(el.innerText||el.getAttribute('aria-label')||'').trim();if(/^add to chrome$|^chrome'a ekle$/i.test(t)){el.dataset.gkInstall='1';if(el instanceof HTMLElement)el.innerText="GenişKapı'ya ekle"}});document.addEventListener('click',event=>{const el=event.target instanceof Element?event.target.closest('[data-gk-install],button,[role="button"],a'):null;if(!el)return;const t=(el.innerText||'').trim();if(el.dataset.gkInstall!=='1'&&!/chrome'a ekle|add to chrome/i.test(t))return;const id=getId();if(!id)return;event.preventDefault();event.stopPropagation();event.stopImmediatePropagation();location.href='geniskapi://install/'+id+'?source='+encodeURIComponent(location.href)},true);new MutationObserver(()=>{hide();mark()}).observe(document.documentElement,{childList:true,subtree:true});hide();mark()})();`; try { await contents.executeJavaScript(bridge, true); } catch {} }); }
function configureSession() { session.defaultSession.webRequest.onBeforeRequest(filter, (details, callback) => callback({ cancel: shouldBlock(details.url) })); session.defaultSession.webRequest.onBeforeSendHeaders((details, callback) => { details.requestHeaders['User-Agent'] = CHROME_UA; callback({ requestHeaders: details.requestHeaders }); }); session.defaultSession.setPermissionRequestHandler((_, permission, callback) => callback(new Set(['clipboard-read', 'clipboard-write', 'notifications']).has(permission))); session.defaultSession.on('will-download', (_, item) => { const target = path.join(app.getPath('downloads'), item.getFilename()); item.setSavePath(target); win?.webContents.send('download-started', { filename: item.getFilename(), path: target }); item.on('updated', (_, state) => win?.webContents.send('download-progress', { filename: item.getFilename(), state, receivedBytes: item.getReceivedBytes(), totalBytes: item.getTotalBytes() })); item.once('done', (_, state) => win?.webContents.send('download-finished', { filename: item.getFilename(), path: target, state })); }); }
function wireTab(tab) { const wc = tab.view.webContents; wc.setUserAgent(CHROME_UA); wc.on('will-navigate', async (event, url) => { if (!url.startsWith('geniskapi://install/')) return; event.preventDefault(); try { const u = new URL(url); const id = u.pathname.replace(/^\//, '').split('/').pop(); const source = u.searchParams.get('source') || ''; const result = await installChromeWebStoreExtension(id, source); win.webContents.send('extension-install-result', result); } catch (error) { showExtensionIncompatibility('Bu eklenti', error.message); } }); wc.setWindowOpenHandler(({ url }) => { createTab(url, true); return { action: 'deny' }; }); wc.on('did-start-loading', () => { tab.loading = true; emitTabs(); if (tab.id === activeTabId) win.webContents.send('page-loading', { id: tab.id, loading: true }); }); wc.on('did-stop-loading', () => { tab.loading = false; emitTabs(); if (tab.id === activeTabId) win.webContents.send('page-loading', { id: tab.id, loading: false }); }); wc.on('page-title-updated', (_, title) => { tab.title = cleanTitle(title, tab.url); emitTabs(); win.webContents.send('page-title', { id: tab.id, title: tab.title }); }); wc.on('did-navigate', (_, url) => { tab.url = url; tab.title = cleanTitle('', url); emitTabs(); win.webContents.send('page-url', { id: tab.id, url, title: tab.title }); injectCwsBridge(wc); }); wc.on('did-navigate-in-page', (_, url) => { tab.url = url; emitTabs(); win.webContents.send('page-url', { id: tab.id, url, title: tab.title }); if (isCwsUrl(url)) injectCwsBridge(wc); }); wc.on('render-process-gone', (_, details) => { tab.title = 'Sekme kurtarıldı'; tab.loading = false; emitTabs(); win?.webContents.send('tab-crashed', { id: tab.id, reason: details.reason }); }); }
function createTab(url = 'https://www.google.com/', activate = true) { const id = nextTabId++; const view = new BrowserView({ webPreferences: { contextIsolation: true, sandbox: true, nodeIntegration: false } }); const tab = { id, view, title: 'Yeni sekme', url, loading: true }; tabs.set(id, tab); wireTab(tab); if (activate) attachTab(tab); else layoutView(tab); view.webContents.loadURL(url).catch(error => { tab.loading = false; tab.title = 'Sayfa yüklenemedi'; win?.webContents.send('tab-error', { id, error: error.message, url }); emitTabs(); }); emitTabs(); return id; }
function selectTab(id) { const tab = tabs.get(Number(id)); if (!tab) return false; if (activeTabId && tabs.has(activeTabId)) detachTab(tabs.get(activeTabId)); attachTab(tab); win.webContents.send('page-url', { id: tab.id, url: tab.url, title: tab.title }); win.webContents.send('page-loading', { id: tab.id, loading: tab.loading }); return true; }
function closeTab(id) { id = Number(id); const tab = tabs.get(id); if (!tab) return false; const wasActive = activeTabId === id; if (wasActive) detachTab(tab); tabs.delete(id); try { tab.view.webContents.destroy(); } catch {} if (wasActive) { const remaining = [...tabs.values()]; const next = remaining[remaining.length - 1]; if (next) attachTab(next); else createTab('https://www.google.com/', true); } emitTabs(); return true; }
function duplicateTab(id) { const tab = tabs.get(Number(id)); if (!tab) return false; return createTab(tab.url || 'https://www.google.com/', true); }
function createWindow() { win = new BrowserWindow({ width: 1440, height: 900, minWidth: 900, minHeight: 600, backgroundColor: '#08111f', title: 'GenişKapı Browser', webPreferences: { preload: path.join(__dirname, 'preload.js'), contextIsolation: true, sandbox: true, nodeIntegration: false } }); win.setMenuBarVisibility(false); const resize = () => { const current = activeTab(); if (current) layoutView(current); }; win.on('resize', resize); win.on('maximize', () => win.webContents.send('window-state', { maximized: true })); win.on('unmaximize', () => win.webContents.send('window-state', { maximized: false })); win.webContents.on('did-finish-load', () => { try { const css = fs.readFileSync(path.join(__dirname, 'animations.css'), 'utf8'); win.webContents.insertCSS(css).catch(() => {}); const modern = fs.readFileSync(path.join(__dirname, 'modern-ui.css'), 'utf8'); win.webContents.insertCSS(modern).catch(() => {}); } catch {} emitTabs(); }); createTab('https://www.google.com/', true); }
app.whenReady().then(async () => { extensionStoreFile = path.join(app.getPath('userData'), 'installed-extensions.json'); configureSession(); await restoreExtensions(); createWindow(); Menu.setApplicationMenu(Menu.buildFromTemplate([{ label: 'GenişKapı', submenu: [{ role: 'about' }, { role: 'quit' }] }, { label: 'Görünüm', submenu: [{ role: 'toggledevtools' }, { role: 'reload' }, { role: 'togglefullscreen' }] }])); });

ipcMain.handle('navigate', (_, value) => { const tab = activeTab(); if (!tab) return false; let u = String(value || '').trim(); if (!/^https?:\/\//i.test(u)) u = `https://www.google.com/search?q=${encodeURIComponent(u)}`; tab.url = u; tab.title = cleanTitle('', u); tab.view.webContents.loadURL(u); emitTabs(); return true; });
ipcMain.handle('back', () => activeTab()?.view.webContents.goBack());
ipcMain.handle('forward', () => activeTab()?.view.webContents.goForward());
ipcMain.handle('reload', () => activeTab()?.view.webContents.reload());
ipcMain.handle('home', () => activeTab()?.view.webContents.loadURL('https://www.google.com/'));
ipcMain.handle('new-window', () => { const w = new BrowserWindow({ width: 1200, height: 800, webPreferences: { contextIsolation: true, sandbox: true, nodeIntegration: false } }); w.webContents.setUserAgent(CHROME_UA); w.loadURL('https://www.google.com/'); });
ipcMain.handle('tab-new', () => createTab('https://www.google.com/', true));
ipcMain.handle('tab-select', (_, id) => selectTab(id));
ipcMain.handle('tab-close', (_, id) => closeTab(id));
ipcMain.handle('tab-duplicate', (_, id) => duplicateTab(id));
ipcMain.handle('tab-list', () => [...tabs.values()].map(tabSnapshot));
ipcMain.handle('window-minimize', () => win?.minimize());
ipcMain.handle('window-maximize', () => { if (win?.isMaximized()) win.unmaximize(); else win?.maximize(); });
ipcMain.handle('window-close', () => win?.close());
ipcMain.handle('cws-install', async (_, id, url) => installChromeWebStoreExtension(id, url));
ipcMain.handle('extensions-list', () => [...extensions.values()]);
ipcMain.handle('extensions-remove', async (_, id) => { if (!extensions.has(id)) return false; try { await session.defaultSession.removeExtension(id); } catch {} extensions.delete(id); writeInstalledExtensions(); return true; });
app.on('window-all-closed', () => { if (process.platform !== 'darwin') app.quit(); });
