const { app, BrowserWindow, BrowserView, ipcMain, session, Menu, net } = require('electron');
const path = require('path');
const fs = require('fs');
const AdmZip = require('adm-zip');

const CHROME_UA = `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/${process.versions.chrome || '150.0.0.0'} Safari/537.36`;
const CWS_HOSTS = new Set(['chromewebstore.google.com', 'chrome.google.com']);
const filter = { urls: ['*://*/*'] };
const blocked = new Set(['doubleclick.net','googlesyndication.com','googleadservices.com','adnxs.com','adsrvr.org','scorecardresearch.com','zedo.com']);
const SIDEBAR_WIDTH = 72;
let win, extensionStoreFile, activeTabId = null, nextTabId = 1;
const tabs = new Map(), extensions = new Map();
function shouldBlock(url){try{const h=new URL(url).hostname.replace(/^www\./,'').toLowerCase();return blocked.has(h)||[...blocked].some(d=>h.endsWith(`.${d}`))}catch{return false}}
function isCwsUrl(url){try{return CWS_HOSTS.has(new URL(url).hostname.toLowerCase())}catch{return false}}
function readInstalledExtensions(){try{if(!fs.existsSync(extensionStoreFile))return[];const d=JSON.parse(fs.readFileSync(extensionStoreFile,'utf8'));return Array.isArray(d)?d:[]}catch{return[]}}
function writeInstalledExtensions(){fs.mkdirSync(path.dirname(extensionStoreFile),{recursive:true});fs.writeFileSync(extensionStoreFile,JSON.stringify([...extensions.values()],null,2),'utf8')}
function uiProgress(p){win?.webContents.send('extension-install-progress',p)}
function cleanTitle(t,u){if(t&&t.trim())return t.trim();try{return new URL(u).hostname||'Yeni sekme'}catch{return'Yeni sekme'}}
function tabSnapshot(t){return{id:t.id,title:t.title,url:t.url,loading:!!t.loading,active:t.id===activeTabId,canGoBack:t.view.webContents.canGoBack(),canGoForward:t.view.webContents.canGoForward()}}
function emitTabs(){if(!win||win.isDestroyed())return;win.webContents.send('tabs-updated',[...tabs.values()].map(tabSnapshot));if(activeTabId)win.webContents.send('active-tab',activeTabId)}
function activeTab(){return activeTabId?tabs.get(activeTabId):null}
function getBounds(){const b=win.getBounds();return{x:SIDEBAR_WIDTH,y:112,width:Math.max(0,b.width-SIDEBAR_WIDTH),height:Math.max(0,b.height-112)}}
function layoutView(t){if(!t||t.view.isDestroyed())return;t.view.setBounds(getBounds());t.view.setAutoResize({width:true,height:true})}
function attachTab(t){if(!t)return;layoutView(t);win.setBrowserView(t.view);activeTabId=t.id;emitTabs()}
function detachTab(t){try{if(t&&win.getBrowserView()===t.view)win.setBrowserView(null)}catch{}}
function parseCrx(buffer){const b=Buffer.from(buffer);if(b.length<16||b.subarray(0,4).toString()!=='Cr24')throw new Error('Geçersiz CRX paketi');const v=b.readUInt32LE(4);if(v===2){const p=b.readUInt32LE(8),s=b.readUInt32LE(12),o=16+p+s;if(o>=b.length)throw new Error('Bozuk CRX2 paketi');return b.subarray(o)}if(v===3){const h=b.readUInt32LE(8),o=12+h;if(o>=b.length)throw new Error('Bozuk CRX3 paketi');return b.subarray(o)}throw new Error(`Desteklenmeyen CRX sürümü: ${v}`)}
function readManifest(dir){const file=path.join(dir,'manifest.json');if(!fs.existsSync(file))throw new Error('Uzantı manifest.json içermiyor');const m=JSON.parse(fs.readFileSync(file,'utf8'));if(!m.name||!m.version||!m.manifest_version)throw new Error('Geçersiz uzantı manifesti');if(![2,3].includes(Number(m.manifest_version)))throw new Error(`Manifest Version ${m.manifest_version} GenişKapı tarafından desteklenmiyor`);return m}
function showExtensionIncompatibility(name,reason){if(!win||win.isDestroyed())return;const d=new BrowserWindow({width:520,height:430,parent:win,modal:true,resizable:false,backgroundColor:'#060b13',title:'GenişKapı • Eklenti uyumluluğu',webPreferences:{contextIsolation:true,sandbox:true,nodeIntegration:false}});d.loadFile(path.join(__dirname,'extension-error.html'),{query:{name:name||'Bu eklenti',reason:String(reason||'Uyumluluk denetimi başarısız.')}});d.setMenuBarVisibility(false)}
async function downloadCrx(id){const u=`https://clients2.google.com/service/update2/crx?response=redirect&prodversion=${encodeURIComponent(process.versions.chrome||'150.0.0.0')}&acceptformat=crx3,crx2&x=id%3D${encodeURIComponent(id)}%26uc`;const r=await net.fetch(u,{headers:{'User-Agent':CHROME_UA,Accept:'*/*'}});if(!r.ok)throw new Error(`Chrome Web Store indirme başarısız (${r.status})`);return Buffer.from(await r.arrayBuffer())}
async function installChromeWebStoreExtension(id,storeUrl=''){id=String(id||'').toLowerCase();if(!/^[a-z]{32}$/.test(id))throw new Error('Geçerli Chrome Web Store uzantı kimliği bulunamadı');if(extensions.has(id))return{ok:true,alreadyInstalled:true,extension:extensions.get(id)};uiProgress({id,stage:'download',progress:5,text:'Uzantı indiriliyor…'});const crx=await downloadCrx(id),zip=parseCrx(crx),base=path.join(app.getPath('userData'),'extensions'),finalDir=path.join(base,id),temp=path.join(base,`${id}.installing-${Date.now()}`);fs.mkdirSync(base,{recursive:true});fs.mkdirSync(temp,{recursive:true});let name='Bu eklenti';try{new AdmZip(zip).extractAllTo(temp,true);const m=readManifest(temp);name=m.name||name;uiProgress({id,stage:'unpack',progress:60,text:'Uzantı hazırlanıyor…'});if(fs.existsSync(finalDir))fs.rmSync(finalDir,{recursive:true,force:true});fs.renameSync(temp,finalDir);const loaded=await session.defaultSession.loadExtension(finalDir,{allowFileAccess:true}).catch(e=>{throw new Error(`GenişKapı bu uzantıyı yükleyemedi: ${e.message}`)});const rec={id:loaded.id||id,name,version:m.version,manifestVersion:m.manifest_version,path:finalDir,source:'Chrome Web Store',storeUrl:storeUrl||`https://chromewebstore.google.com/detail/${id}`};extensions.set(rec.id,rec);writeInstalledExtensions();win?.webContents.send('extension-installed',rec);uiProgress({id:rec.id,stage:'done',progress:100,text:`${rec.name} kuruldu`});return{ok:true,extension:rec}}catch(e){try{fs.rmSync(temp,{recursive:true,force:true})}catch{}try{fs.rmSync(finalDir,{recursive:true,force:true})}catch{}showExtensionIncompatibility(name,e.message);win?.webContents.send('extension-install-error',{id,error:e.message,incompatible:true});return{ok:false,incompatible:true,error:e.message}}}
async function restoreExtensions(){for(const item of readInstalledExtensions()){try{if(!item.path||!fs.existsSync(item.path))continue;const m=readManifest(item.path),loaded=await session.defaultSession.loadExtension(item.path,{allowFileAccess:true});extensions.set(loaded.id||item.id,{...item,id:loaded.id||item.id,name:m.name,version:m.version})}catch(e){console.warn('[GenişKapı] Uzantı yüklenemedi:',item.id,e.message)}}writeInstalledExtensions()}
function injectCwsBridge(contents){contents.on('did-finish-load',async()=>{if(!isCwsUrl(contents.getURL()))return;const bridge=`(()=>{const id=()=>{const m=location.pathname.match(/\\/detail\\/[^/]+\\/([a-z]{32})/i);return m?m[1].toLowerCase():null};const mark=()=>document.querySelectorAll('button,[role="button"],a').forEach(el=>{const t=(el.innerText||el.getAttribute('aria-label')||'').trim();if(/^add to chrome$|^chrome'a ekle$/i.test(t)){el.dataset.gk='1';if(el instanceof HTMLElement)el.innerText="GenişKapı'ya ekle"}});document.addEventListener('click',e=>{const el=e.target instanceof Element?e.target.closest('[data-gk],button,[role="button"],a'):null;if(!el)return;const t=(el.innerText||'').trim();if(el.dataset.gk!=='1'&&!/chrome'a ekle|add to chrome/i.test(t))return;const x=id();if(!x)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();location.href='geniskapi://install/'+x+'?source='+encodeURIComponent(location.href)},true);new MutationObserver(mark).observe(document.documentElement,{childList:true,subtree:true});mark()})();`;try{await contents.executeJavaScript(bridge,true)}catch{}})}
function configureSession(){session.defaultSession.webRequest.onBeforeRequest(filter,(d,cb)=>cb({cancel:shouldBlock(d.url)}));session.defaultSession.webRequest.onBeforeSendHeaders((d,cb)=>{d.requestHeaders['User-Agent']=CHROME_UA;cb({requestHeaders:d.requestHeaders})});session.defaultSession.setPermissionRequestHandler((_,p,cb)=>cb(new Set(['clipboard-read','clipboard-write','notifications']).has(p)));session.defaultSession.on('will-download',(_,item)=>{const target=path.join(app.getPath('downloads'),item.getFilename());item.setSavePath(target);win?.webContents.send('download-started',{filename:item.getFilename(),path:target});item.on('updated',(_,state)=>win?.webContents.send('download-progress',{filename:item.getFilename(),state,receivedBytes:item.getReceivedBytes(),totalBytes:item.getTotalBytes()}));item.once('done',(_,state)=>win?.webContents.send('download-finished',{filename:item.getFilename(),path:target,state}))})}
function wireTab(tab){const wc=tab.view.webContents;wc.setUserAgent(CHROME_UA);wc.on('will-navigate',async(e,url)=>{if(!url.startsWith('geniskapi://install/'))return;e.preventDefault();try{const u=new URL(url),id=u.pathname.replace(/^\//,'').split('/').pop(),source=u.searchParams.get('source')||'';const result=await installChromeWebStoreExtension(id,source);win.webContents.send('extension-install-result',result)}catch(err){showExtensionIncompatibility('Bu eklenti',err.message)}});wc.setWindowOpenHandler(({url})=>{createTab(url,true);return{action:'deny'}});wc.on('did-start-loading',()=>{tab.loading=true;emitTabs()});wc.on('did-stop-loading',()=>{tab.loading=false;emitTabs()});wc.on('page-title-updated',(_,title)=>{tab.title=cleanTitle(title,tab.url);emitTabs();win.webContents.send('page-title',{id:tab.id,title:tab.title})});wc.on('did-navigate',(_,url)=>{tab.url=url;tab.title=cleanTitle('',url);emitTabs();win.webContents.send('page-url',{id:tab.id,url,title:tab.title});injectCwsBridge(wc)});wc.on('did-navigate-in-page',(_,url)=>{tab.url=url;emitTabs();win.webContents.send('page-url',{id:tab.id,url,title:tab.title});if(isCwsUrl(url))injectCwsBridge(wc)});wc.on('render-process-gone',(_,d)=>{tab.title='Sekme kurtarılabilir';tab.loading=false;emitTabs();win?.webContents.send('tab-crashed',{id:tab.id,reason:d.reason})})}
function createTab(url='https://www.google.com/',activate=true){const id=nextTabId++,view=new BrowserView({webPreferences:{contextIsolation:true,sandbox:true,nodeIntegration:false}}),tab={id,view,title:'Yeni sekme',url,loading:true};tabs.set(id,tab);wireTab(tab);if(activate)attachTab(tab);else layoutView(tab);view.webContents.loadURL(url).catch(error=>{tab.loading=false;tab.title='Sayfa yüklenemedi';win?.webContents.send('tab-error',{id,error:error.message,url});emitTabs()});emitTabs();return id}
function selectTab(id){const tab=tabs.get(Number(id));if(!tab)return false;if(activeTabId&&tabs.has(activeTabId))detachTab(tabs.get(activeTabId));attachTab(tab);win.webContents.send('page-url',{id:tab.id,url:tab.url,title:tab.title});win.webContents.send('page-loading',{id:tab.id,loading:tab.loading});return true}
function closeTab(id){id=Number(id);const tab=tabs.get(id);if(!tab)return false;const wasActive=activeTabId===id;if(wasActive)detachTab(tab);tabs.delete(id);try{tab.view.webContents.destroy()}catch{}if(wasActive){const left=[...tabs.values()];const next=left[left.length-1];if(next)attachTab(next);else createTab('https://www.google.com/',true)}emitTabs();return true}
function duplicateTab(id){const tab=tabs.get(Number(id));return tab?createTab(tab.url,true):false}
function createWindow(){win=new BrowserWindow({width:1440,height:900,minWidth:900,minHeight:600,backgroundColor:'#08111f',title:'GenişKapı Browser',webPreferences:{preload:path.join(__dirname,'preload.js'),contextIsolation:true,sandbox:true,nodeIntegration:false}});win.setMenuBarVisibility(false);win.on('resize',()=>{const t=activeTab();if(t)layoutView(t)});win.on('maximize',()=>win.webContents.send('window-state',{maximized:true}));win.on('unmaximize',()=>win.webContents.send('window-state',{maximized:false}));win.webContents.on('did-finish-load',()=>{for(const f of ['animations.css','modern-ui.css']){try{win.webContents.insertCSS(fs.readFileSync(path.join(__dirname,f),'utf8')).catch(()=>{})}catch{}}emitTabs()});win.loadFile(path.join(__dirname,'ui-v2.html'));createTab('https://www.google.com/',true)}
app.whenReady().then(async()=>{extensionStoreFile=path.join(app.getPath('userData'),'installed-extensions.json');configureSession();await restoreExtensions();createWindow();Menu.setApplicationMenu(Menu.buildFromTemplate([{label:'GenişKapı',submenu:[{role:'about'},{role:'quit'}]},{label:'Görünüm',submenu:[{role:'toggledevtools'},{role:'reload'},{role:'togglefullscreen'}]}]))});
ipcMain.handle('navigate',(_,value)=>{const tab=activeTab();if(!tab)return false;let u=String(value||'').trim();if(!/^https?:\/\//i.test(u))u='https://www.google.com/search?q='+encodeURIComponent(u);tab.url=u;tab.view.webContents.loadURL(u);emitTabs();return true});ipcMain.handle('back',()=>activeTab()?.view.webContents.goBack());ipcMain.handle('forward',()=>activeTab()?.view.webContents.goForward());ipcMain.handle('reload',()=>activeTab()?.view.webContents.reload());ipcMain.handle('home',()=>activeTab()?.view.webContents.loadURL('https://www.google.com/'));ipcMain.handle('new-window',()=>{const w=new BrowserWindow({width:1200,height:800,webPreferences:{contextIsolation:true,sandbox:true,nodeIntegration:false}});w.webContents.setUserAgent(CHROME_UA);w.loadURL('https://www.google.com/')});ipcMain.handle('tab-new',()=>createTab('https://www.google.com/',true));ipcMain.handle('tab-select',(_,id)=>selectTab(id));ipcMain.handle('tab-close',(_,id)=>closeTab(id));ipcMain.handle('tab-duplicate',(_,id)=>duplicateTab(id));ipcMain.handle('tab-list',()=>[...tabs.values()].map(tabSnapshot));ipcMain.handle('window-minimize',()=>win?.minimize());ipcMain.handle('window-maximize',()=>{if(win?.isMaximized())win.unmaximize();else win?.maximize()});ipcMain.handle('window-close',()=>win?.close());ipcMain.handle('cws-install',(_,id,url)=>installChromeWebStoreExtension(id,url));ipcMain.handle('extensions-list',()=>[...extensions.values()]);ipcMain.handle('extensions-remove',async(_,id)=>{if(!extensions.has(id))return false;try{await session.defaultSession.removeExtension(id)}catch{}extensions.delete(id);writeInstalledExtensions();return true});app.on('window-all-closed',()=>{if(process.platform!=='darwin')app.quit()});
