const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('geniskapi', {
  navigate: value => ipcRenderer.invoke('navigate', value),
  back: () => ipcRenderer.invoke('back'),
  forward: () => ipcRenderer.invoke('forward'),
  reload: () => ipcRenderer.invoke('reload'),
  home: () => ipcRenderer.invoke('home'),
  newWindow: () => ipcRenderer.invoke('new-window'),
  newTab: () => ipcRenderer.invoke('tab-new'),
  selectTab: id => ipcRenderer.invoke('tab-select', id),
  closeTab: id => ipcRenderer.invoke('tab-close', id),
  duplicateTab: id => ipcRenderer.invoke('tab-duplicate', id),
  getTabs: () => ipcRenderer.invoke('tab-list'),
  minimize: () => ipcRenderer.invoke('window-minimize'),
  maximize: () => ipcRenderer.invoke('window-maximize'),
  closeWindow: () => ipcRenderer.invoke('window-close'),
  openInternal: page => ipcRenderer.invoke('internal-open', page),
  historyList: query => ipcRenderer.invoke('history-list', query || ''),
  historyAdd: entry => ipcRenderer.invoke('history-add', entry),
  historyClear: () => ipcRenderer.invoke('history-clear'),
  bookmarksList: folder => ipcRenderer.invoke('bookmarks-list', folder || null),
  bookmarkAdd: item => ipcRenderer.invoke('bookmark-add', item),
  bookmarkRemove: url => ipcRenderer.invoke('bookmark-remove', url),
  bookmarkFind: url => ipcRenderer.invoke('bookmark-find', url),
  downloadsList: () => ipcRenderer.invoke('downloads-list'),
  extensionsList: () => ipcRenderer.invoke('extensions-list'),
  extensionsRemove: id => ipcRenderer.invoke('extensions-remove', id),
  onTabs: cb => ipcRenderer.on('tabs-updated', (_, tabs) => cb(tabs)),
  onUrl: cb => ipcRenderer.on('page-url', (_, data) => cb(data)),
  onTitle: cb => ipcRenderer.on('page-title', (_, data) => cb(data)),
  onLoading: cb => ipcRenderer.on('page-loading', (_, data) => cb(data)),
  onActiveTab: cb => ipcRenderer.on('active-tab', (_, id) => cb(id)),
  onWindowState: cb => ipcRenderer.on('window-state', (_, state) => cb(state)),
  onTabCrashed: cb => ipcRenderer.on('tab-crashed', (_, data) => cb(data)),
  onTabError: cb => ipcRenderer.on('tab-error', (_, data) => cb(data)),
  onDownloadStarted: cb => ipcRenderer.on('download-started', (_, data) => cb(data)),
  onDownloadProgress: cb => ipcRenderer.on('download-progress', (_, data) => cb(data)),
  onDownloadFinished: cb => ipcRenderer.on('download-finished', (_, data) => cb(data)),
  onExtensionInstalled: cb => ipcRenderer.on('extension-installed', (_, data) => cb(data)),
  onExtensionError: cb => ipcRenderer.on('extension-install-error', (_, data) => cb(data))
});
